name: CI
on: [push]
jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.5"

      - name: tox install
        run: pip install tox

      - name: Python 3.5, Django 1.11 Unit Tests
        run: tox -e py35-django111

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
